import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>栂池ロッヂかどや</h1>

        <p className={styles.description}>ゲレンデの中にある民宿</p>

        <div className={styles.grid}>
          {/* NEXT LINK に切り替える */}
          <Link href={"/cooking"}>
            <a className={styles.card}>
              <h2>お料理 &rarr;</h2>
              <p>自家製野菜を使用しております。</p>
            </a>
          </Link>
          <Link href={"/reserve"}>
            <a className={styles.card}>
              <h2>ご予約 &rarr;</h2>
              <p>空き状況もご確認いただけます。</p>
            </a>
          </Link>
          <Link href={"/contact"}>
            <a className={styles.card}>
              <h2>お問い合わせ &rarr;</h2>
              <p>お気軽にお問い合わせください</p>
            </a>
          </Link>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>アクセス &rarr;</h2>
            <p>アクセス方法はこちら。</p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default Home;
