import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home = () => {
  return (
    <div>
      <Head>
        <title>栂池ロッヂかどや</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>栂池ロッヂかどや</h1>

        <p>ゲレンデの中にある民宿</p>

        <div>
          {/* NEXT LINK に切り替える */}
          <Link href={"/cooking"}>
            <a>
              <h2>お料理 &rarr;</h2>
              <p>自家製野菜を使用しております。</p>
            </a>
          </Link>
          <Link href={"/reserve"}>
            <a>
              <h2>ご予約 &rarr;</h2>
              <p>空き状況もご確認いただけます。</p>
            </a>
          </Link>
          <Link href={"/contact"}>
            <a>
              <h2>お問い合わせ &rarr;</h2>
              <p>お気軽にお問い合わせください</p>
            </a>
          </Link>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>アクセス &rarr;</h2>
            <p>アクセス方法はこちら。</p>
          </a> */}
        </div>
      </main>

      <footer>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default Home;
