import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

const Guidance = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ご案内を示す部分</h1>
      </main>

      <footer className={styles.footer}>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default Guidance;
