import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

const PriceSheet = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>料金表を表示する部分</h1>

        <p className={styles.description}>ゲレンデの中にある民宿</p>
        <div className={styles.grid}>あああ</div>
      </main>

      <footer className={styles.footer}>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default PriceSheet;
