import Head from "next/head";

const PriceSheet = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>料金表を表示する部分</h1>

        <p>ゲレンデの中にある民宿</p>
        <div>あああ</div>
      </main>

      <footer>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default PriceSheet;
