import Head from "next/head";

const Neighborhood = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>周辺情報を示す部分</h1>
      </main>

      <footer>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default Neighborhood;
