import Head from "next/head";
import Image from "next/image";

const Access = () => {
  return (
    <div>
      <Head>
        <title>栂池ロッヂかどや</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>アクセスを示す部分</h1>
      </main>

      <footer>
        <p>フッターだよ</p>
      </footer>
    </div>
  );
};

export default Access;
